apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-parser-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steam-parser
  template:
    metadata:
      labels:
        app: steam-parser
    spec:
      containers:
        - image: tjasad/rso-steam-parser:latest
          name: steam-parser
          resources:
            limits:
              memory: 512Mi
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
            - containerPort: 9000
              name: grpc


---

apiVersion: v1
kind: Service
metadata:
  name: steam-parser
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: server
      protocol: TCP
    - port: 9000
      targetPort: grpc
  selector:
    app: steam-parser