apiVersion: apps/v1
kind: Deployment
metadata:
  name: steam-parser-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steam-parser
  template:
    metadata:
      labels:
        app: steam-parser
    spec:
      containers:
        - image: tjasad/rso-steam-parser:latest
          name: steam-parser
          resources:
            limits:
              memory: 512Mi
          ports:
            - containerPort: 9000
              name: grpc-server
              protocol: TCP
          env:
            - name: QUARKUS_GRPC_SERVER_HOST
              value: 0.0.0.0

---

apiVersion: v1
kind: Service
metadata:
  name: steam-parser
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
  selector:
    app: steam-parser